<a href="https://colab.research.google.com/github/zolfaShefreie/Empathy_Detection/blob/main/preprocess_merge_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
pd.set_option('display.max_colwidth', None)

In [2]:
epitome_df = pd.read_csv("/content/Epitome.csv")
emp_conv_df = pd.read_csv("/content/empathetic_conversation.csv")
iempathize_df = pd.read_csv("/content/iEmpathize.csv")
news_df = pd.read_csv("/content/newsReactions.csv")

##preprocess

In [4]:
epitome_df

,Unnamed: 0,sp_id,rp_id,seeker_post,response_post,level_interpretations,rationales_interpretations,level_emotional_reactions,rationales_emotional_reactions,level_explorations,rationales_explorations
0,0,65m92s,dgbdk7z,Help. Help me. I dunno what I'm doing anymore,"That's pretty vague, do you not know what you're doing in regards to a specific section of your life? Like school or work?",0.0,NaN,0.0,NaN,2.0,do you not know what you're doing in regards to a specific section of your life? Like school or work?|
1,1,9ezsfi,e5t3oxh,I'm done saying I love you to her because I don't want to hear a lie back to me. I feel so ugly and unwanted and unloved,"idk what a Red pill means exactly but my advice to you is if she treating you right then fuck her there are billions of other girls out there, and if u feel like in love with her and just leave her then try to not care and you have to accept the fact that some girls(as well as some guys) will lie straight to your face for years without any remorse. my advice is stop caring before too late.",0.0,NaN,0.0,NaN,0.0,NaN
2,2,6b2cmc,dhj8tcb,Always feel like I'm being criticized and mocked even when alone.... Does anyone else experience this?,"I think it's social anxiety , that creates paranoid feelings , unless I'm wrong but that's how I feel",2.0,unless I'm wrong but that's how I feel|,0.0,NaN,0.0,NaN
3,3,8iz0as,dyvq1ne,"My diet becomes fucked when i get depressed.. I can't control myself in the grocery store when I'm feeling down. Chips, cookies, soda, cake, you name It. Anyone else a stress eater?","By any chance do you think you're in a loop. Junk food can make you depressed. And being depressed probably makes you eat more junk food? For a while that was my problem too. Even if its just random, ill probably binge and feel bad later. Only to indulge in more later to try to cheer up.",2.0,"For a while that was my problem too. Even if its just random, ill probably binge and feel bad later. Only to indulge in more later to try to cheer up.|",0.0,NaN,2.0,By any chance do you think you're in a loop|
4,4,aow3l9,eg40ecq,"I hate not knowing why. I was diagnosed with depression and anxiety when I was 14. That's almost 4 years ago and I still don't know why I am like this. I have more than enough, yet there are moments where I feel like there's no hope nor a bright future waiting for me. I feel alone and abandoned even though I have friends who know that I am depressed and am like this sometimes. I get so frustrated when I can't find out why I just can't be normal. Everything was alright about 2 hours ago, but it just changes so quickly and hard that I almost feel suicidal. I'm a fucking mess...","depression. not sadness which is caused by something and is healthy. Depression is an actual mental disorder which commonly goes untreated. The best things you can do for depression is first of all, not hiding it, tell your loved ones so they can help you. also get a therapist, very helpful and help you cope with depression and get over it. If you think really bad you can see a doctor and see if medication is a good idea. I take antidepressants and my depression is gone, it change you like I originally thought it would, it just makes me the same but not sad all the time.",2.0,"I take antidepressants and my depression is gone, it change you like I originally thought it would, it just makes me the same but not sad all the time.|",0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3682,6038,9o5997,e7rtgm7,"If I get caught will I end up in a psych ward?. I'm planning on killing myself and was wondering if i somehow survived,would i get put in a psych ward for the rest of my life?","Depends what you mean by get caught. Someone would have to report it to police to move you anywhere or if you're under 18 parents can take you to a hospital. Basic detainment is 72 hours (3 days) To ensure you're not a harm to yourself or others. During that time they examine you and see your mental state. If at the end you're not showing signs of danger you are released but given options to stay for further treatment. If you are still a danger you stay and get more treatment. Now say you made an attempt and go to the ER for something, they can't always just detain you. I've been to the ER for atempt of suicide by oversosing on medication. Longest I was there was a few hours. Due to my mental state being stable they had no legal way to hold me loner than I wanted to be there. I got the drugs out of my system then was discharged and went home. There is a ton, a shit ton of misinformation and propaganda around mental illness. Be informed, do real research. isn't google. You are smart enough to do real research don't just ask strangers online for all the answers. Also get help.",0.0,NaN,0.0,NaN,0.0,NaN
3683,6039,5xtisn,dekpofh,Why am I so fucked up?. I just bombed my bio test and ruined my whole quarter. I went into the bathroom and purged my breakfast out. Now I'm crying in the bathroom floor in the school and Idk what the fuck to do next.,"Talk to your teacher. Sometimes they're willing to give extra credit if you do additional assignments or labs. Also, many teachers will at least pass a student if the student goes to them and shows that they're really making an effort in the class. One test will not ruin your life. I promise. :)",0.0,NaN,1.0,One test will not ruin your life. I promise. :)|,0.0,NaN
3684,6042,8lfufr,dzfd8cg,"How do you handle people that pray on your depression/anxiety?. Sadly, I have friends that pray on my depression/anxiety. There's always something to disagree with or some snide comment to make. How do you guys cope with this? It makes me really anxious, which just leads to anger.","Here is the thing. If you open up to these people and they through it in your face right after, then you know they aren't real friends. A real friend is willing to sit through peoples problems for hours. I once sat and chatted with a friend about his issues for some 7 odd hours hours just talking till 7am, never gave up on the conversation, he did the same for me a while later down the road when I was having problems. People who aren't willing to talk to you and help you aren't worth keeping around. Believe me there is a friend out there who is willing to listen. I guess do keep in mind that not everyone has infinite patients and has their own problems. good luck out there man hope things go well for you. (This isn't to say you can't have acquaintances, people you hang out with, but never get deep)",0.0,NaN,1.0,Believe me there is a friend out there who is willing to listen. I guess do keep in mind that not everyone has infinite patients and has their own problems. good luck out there man hope things go well for you.|,0.0,NaN
3685,6044,4dydd1,d1vi4c7,I need a hug. I fucked up so bad. Thinking about ending it for once and for all. I could really use a hug right now,"*hug* Whatever the situation is that's causing you to feel this way, please remember to exercise compassion towards yourself.",0.0,NaN,2.0,"*hug* Whatever the situation is that's causing you to feel this way, please remember to exercise compassion towards yourself.|",0.0,NaN
3686,6049,7gqrti,dqz05c5,"26 year old male, living at home, low income job, in school (parents paying for it), want to get married to girlfriend who graduates with nursing degree in 5 months. I feel like a deadbeat","I see what you mean, but imagine being 26, living at home with no job, absolutely no way to pay for school, and no girlfriend? I'm 26 with a decent job and live alone with no girlfriend. I tell myself that it's because I don't have a license due to a seizure disorder that I'm striking out with girls, which is probably true is some cases but I can't even see that girl being in one relationship for the rest of her life if she's picky like that.",0.0,NaN,0.0,NaN,0.0,NaN

In [5]:
epitome_df.groupby(['level_interpretations', 'level_emotional_reactions', 'level_explorations']).count()

                                                                    Unnamed: 0  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                       1208
                                                1.0                         53
                                                2.0                        244
                      1.0                       0.0                        575
                                                1.0                         26
                                                2.0                         32
                      2.0                       0.0                         97
                                                1.0                          2
                                                2.0                         13
1.0                   0.0                       0.0                         74
                                                1.0                          4
                                                2.0                          5
                      1.0                       0.0                         25
                                                2.0                          2
                      2.0                       0.0                          3
2.0                   0.0                       0.0                       1001
                                                1.0                         13
                                                2.0                         66
                      1.0                       0.0                        195
                                                1.0                          5
                                                2.0                          9
                      2.0                       0.0                         35

                                                                    sp_id  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                  1208
                                                1.0                    53
                                                2.0                   244
                      1.0                       0.0                   575
                                                1.0                    26
                                                2.0                    32
                      2.0                       0.0                    97
                                                1.0                     2
                                                2.0                    13
1.0                   0.0                       0.0                    74
                                                1.0                     4
                                                2.0                     5
                      1.0                       0.0                    25
                                                2.0                     2
                      2.0                       0.0                     3
2.0                   0.0                       0.0                  1001
                                                1.0                    13
                                                2.0                    66
                      1.0                       0.0                   195
                                                1.0                     5
                                                2.0                     9
                      2.0                       0.0                    35

                                                                    rp_id  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                  1208
                                                1.0                    53
                                                2.0                   244
                      1.0                       0.0                   575
                                                1.0                    26
                                                2.0                    32
                      2.0                       0.0                    97
                                                1.0                     2
                                                2.0                    13
1.0                   0.0                       0.0                    74
                                                1.0                     4
                                                2.0                     5
                      1.0                       0.0                    25
                                                2.0                     2
                      2.0                       0.0                     3
2.0                   0.0                       0.0                  1001
                                                1.0                    13
                                                2.0                    66
                      1.0                       0.0                   195
                                                1.0                     5
                                                2.0                     9
                      2.0                       0.0                    35

                                                                    seeker_post  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                        1208
                                                1.0                          53
                                                2.0                         244
                      1.0                       0.0                         575
                                                1.0                          26
                                                2.0                          32
                      2.0                       0.0                          97
                                                1.0                           2
                                                2.0                          13
1.0                   0.0                       0.0                          74
                                                1.0                           4
                                                2.0                           5
                      1.0                       0.0                          25
                                                2.0                           2
                      2.0                       0.0                           3
2.0                   0.0                       0.0                        1001
                                                1.0                          13
                                                2.0                          66
                      1.0                       0.0                         195
                                                1.0                           5
                                                2.0                           9
                      2.0                       0.0                          35

                                                                    response_post  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                          1208
                                                1.0                            53
                                                2.0                           244
                      1.0                       0.0                           575
                                                1.0                            26
                                                2.0                            32
                      2.0                       0.0                            97
                                                1.0                             2
                                                2.0                            13
1.0                   0.0                       0.0                            74
                                                1.0                             4
                                                2.0                             5
                      1.0                       0.0                            25
                                                2.0                             2
                      2.0                       0.0                             3
2.0                   0.0                       0.0                          1001
                                                1.0                            13
                                                2.0                            66
                      1.0                       0.0                           195
                                                1.0                             5
                                                2.0                             9
                      2.0                       0.0                            35

                                                                    rationales_interpretations  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                                          0
                                                1.0                                          0
                                                2.0                                          0
                      1.0                       0.0                                          0
                                                1.0                                          0
                                                2.0                                          0
                      2.0                       0.0                                          0
                                                1.0                                          0
                                                2.0                                          0
1.0                   0.0                       0.0                                         74
                                                1.0                                          4
                                                2.0                                          5
                      1.0                       0.0                                         25
                                                2.0                                          2
                      2.0                       0.0                                          3
2.0                   0.0                       0.0                                        994
                                                1.0                                         13
                                                2.0                                         65
                      1.0                       0.0                                        195
                                                1.0                                          5
                                                2.0                                          9
                      2.0                       0.0                                         35

                                                                    rationales_emotional_reactions  \
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                                              0
                                                1.0                                              0
                                                2.0                                              0
                      1.0                       0.0                                            574
                                                1.0                                             26
                                                2.0                                             31
                      2.0                       0.0                                             97
                                                1.0                                              2
                                                2.0                                             13
1.0                   0.0                       0.0                                              0
                                                1.0                                              0
                                                2.0                                              0
                      1.0                       0.0                                             25
                                                2.0                                              2
                      2.0                       0.0                                              3
2.0                   0.0                       0.0                                              0
                                                1.0                                              0
                                                2.0                                              0
                      1.0                       0.0                                            195
                                                1.0                                              5
                                                2.0                                              9
                      2.0                       0.0                                             35

                                                                    rationales_explorations
level_interpretations level_emotional_reactions level_explorations
0.0                   0.0                       0.0                                       0
                                                1.0                                      52
                                                2.0                                     244
                      1.0                       0.0                                       0
                                                1.0                                      26
                                                2.0                                      32
                      2.0                       0.0                                       0
                                                1.0                                       2
                                                2.0                                      13
1.0                   0.0                       0.0                                       0
                                                1.0                                       4
                                                2.0                                       5
                      1.0                       0.0                                       0
                                                2.0                                       2
                      2.0                       0.0                                       0
2.0                   0.0                       0.0                                       0
                                                1.0                                      13
                                                2.0                                      66
                      1.0                       0.0                                       0
                                                1.0                                       5
                                                2.0                                       9
                      2.0                       0.0                                       0

In [6]:
epitome_df['empathy'] = 0
epitome_df.loc[((epitome_df['level_explorations'] != 0)|
               (epitome_df['level_emotional_reactions'] != 0)|
               (epitome_df['level_interpretations'] != 0)), 'empathy'] = 1

In [7]:
epitome_df.groupby('empathy').count()

,Unnamed: 0,sp_id,rp_id,seeker_post,response_post,level_interpretations,rationales_interpretations,level_emotional_reactions,rationales_emotional_reactions,level_explorations,rationales_explorations
empathy,,,,,,,,,,,
0,1208,1208,1208,1208,1208,1208,0,1208,0,1208,0
1,2479,2479,2479,2479,2479,2479,1429,2479,1017,2479,473

In [8]:
emp_conv_df

,conv_id,utterance_idx,prompt,speaker_idx,utterance,ut_len,Empathy,Talker,PL joy,PL trust,...,PL surprise,PL sadness,PL disgust,PL anger,PL anticipation,PL intensity,Sentiment,Emotion,Taxonomy,Intent
0,hit:11054_conv:22108,1,a job I applied and interview for a couple of months ago offered me the job. It was unexpected.,675,a job I applied and interview for a couple of months ago offered me the job. It was unexpected.,95,5,1,0,0,...,1,0,0,0,0,2,"{'sentiment': {'negative': 0.275, 'neutral': 0.437, 'positive': 0.287}}","{'emotion': {'Happy': 0.155295802, 'Fear': 0.4464744761, 'Sad': 0.1470191662, 'Bored': 0.0219080765, 'Angry': 0.0440912977, 'Excited': 0.1852111815}}","{'taxonomy': [{'confidence_score': 0.4104728103, 'tag': 'IMPACT'}, {'confidence_score': 0.199958995, 'tag': 'EDUCATION'}, {'confidence_score': 0.1853818595, 'tag': 'POLITICS'}]}","{'intent': {'news': 0.087, 'query': 0.072, 'spam': 0.311, 'marketing': 0.052, 'feedback': {'score': 0.477, 'tag': {'complaint': 0.11, 'suggestion': 0.035, 'appreciation': 0.855}}}}"
1,hit:11054_conv:22108,2,a job I applied and interview for a couple of months ago offered me the job. It was unexpected.,746,Congrats! How exciting for you.,32,5,2,0,0,...,1,0,0,0,0,2,"{'sentiment': {'negative': 0.005, 'neutral': 0.056, 'positive': 0.939}}","{'emotion': {'Angry': 0.0883550096, 'Sad': 0.0349955947, 'Excited': 0.1870446923, 'Bored': 0.038619849, 'Happy': 0.4874999949, 'Fear': 0.1634848596}}","{'taxonomy': [{'confidence_score': 0.3719808459, 'tag': 'ENTERTAINMENT'}, {'confidence_score': 0.1847059429, 'tag': 'IMPACT'}, {'confidence_score': 0.1410384923, 'tag': 'POLITICS'}]}","{'intent': {'news': 0.028, 'query': 0.112, 'spam': 0.368, 'marketing': 0.065, 'feedback': {'score': 0.426, 'tag': {'complaint': 0.001, 'suggestion': 0.003, 'appreciation': 0.996}}}}"
2,hit:11054_conv:22108,3,a job I applied and interview for a couple of months ago offered me the job. It was unexpected.,675,"thank you, when they called, I did not know who it was at first, then it was, wow I got the job",119,5,1,0,0,...,1,0,0,0,0,2,"{'sentiment': {'negative': 0.031, 'neutral': 0.122, 'positive': 0.847}}","{'emotion': {'Angry': 0.0568077244, 'Excited': 0.3520834064, 'Happy': 0.3395521848, 'Sad': 0.0398050366, 'Bored': 0.0131736383, 'Fear': 0.1985780095}}","{'taxonomy': [{'confidence_score': 0.3560346365, 'tag': 'POLITICS'}, {'confidence_score': 0.3348067403, 'tag': 'IMPACT'}, {'confidence_score': 0.1984399706, 'tag': 'ENTERTAINMENT'}]}","{'intent': {'news': 0.005, 'query': 0.013, 'spam': 0.354, 'marketing': 0.011, 'feedback': {'score': 0.616, 'tag': {'complaint': 0.003, 'suggestion': 0.002, 'appreciation': 0.995}}}}"
3,hit:11054_conv:22108,4,a job I applied and interview for a couple of months ago offered me the job. It was unexpected.,746,That's a long time to hold out hope. I bet you were shocked.,61,5,2,0,0,...,1,0,0,0,0,2,"{'sentiment': {'negative': 0.572, 'neutral': 0.383, 'positive': 0.046}}","{'emotion': {'Angry': 0.1211754311, 'Excited': 0.1074305336, 'Fear': 0.2339460298, 'Happy': 0.2318156633, 'Sad': 0.1769579945, 'Bored': 0.1286743476}}","{'taxonomy': [{'confidence_score': 0.6219481826, 'tag': 'POLITICS'}, {'confidence_score': 0.1707850993, 'tag': 'IMPACT'}, {'confidence_score': 0.1123252288, 'tag': 'ENTERTAINMENT'}]}","{'intent': {'news': 0.018, 'query': 0.145, 'spam': 0.313, 'marketing': 0.01, 'feedback': {'score': 0.514, 'tag': {'complaint': 0.409, 'suggestion': 0.313, 'appreciation': 0.278}}}}"
4,hit:6194_conv:12389,1,Got a Costco cake. For myself.,1,Got a Costco cake. For myself.,30,3,1,1,0,...,0,0,0,0,0,2,"{'sentiment': {'negative': 0.018, 'neutral': 0.232, 'positive': 0.75}}","{'emotion': {'Happy': 0.4695486472, 'Fear': 0.173305568, 'Sad': 0.0350587229, 'Bored': 0.0159803472, 'Angry': 0.0277583428, 'Excited': 0.2783483719}}","{'taxonomy': [{'confidence_score': 0.5549823046, 'tag': 'TASTE'}, {'confidence_score': 0.2484655529, 'tag': 'ENTERTAINMENT'}, {'confidence_score': 0.0904188827, 'tag': 'IMPACT'}]}","{'intent': {'news': 0.012, 'query': 0.037, 'spam': 0.452, 'marketing': 0.196, 'feedback': 0.304}}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1708,hit:481_conv:963,4,When I got an A on my math final I was super shocked_comma_ thought I did terrible.,55,Nice! Good to hear that things worked out for you in the end!,61,4,2,0,0,...,1,0,0,0,0,2,"{'sentiment': {'negative': 0.019, 'neutral': 0.226, 'positive': 0.756}}","{'emotion': {'Angry': 0.0803235033, 'Sad': 0.0118467023, 'Excited': 0.4706748668, 'Bored': 0.0062787329, 'Happy': 0.3762660437, 'Fear': 0.0546101511}}","{'taxonomy': [{'confidence_score': 0.5615804791, 'tag': 'ENTERTAINMENT'}, {'confidence_score': 0.3552082777, 'tag': 'TASTE'}, {'confidence_score': 0.0234531164, 'tag': 'HEALTHY LIVING'}]}","{'intent': {'news': 0.049, 'query': 0.011, 'spam': 0.307, 'marketing': 0.043, 'feedback': {'score': 0.589, 'tag': {'complaint': 0.0, 'suggestion': 0.005, 'appreciation': 0.994}}}}"
1709,hit:5257_conv:10514,1,I was too tired to mow the lawn and do garden work which me and my brother usually do together. As a result_comma_ he had to do it alone.,511,"One day, I was to tired to mow the lawn.",46,3,1,1,0,...,0,0,0,0,0,2,"{'sentiment': {'negative': 0.648, 'neutral': 0.291, 'positive': 0.061}}","{'emotion': {'Happy': 0.0155348269, 'Fear': 0.1076104529, 'Sad': 0.1898855342, 'Bored': 0.5391463336, 'Angry': 0.1283501895, 'Excited': 0.0194726629}}","{'taxonomy': [{'confidence_score': 0.5075516701, 'tag': 'ENTERTAINMENT'}, {'confidence_score': 0.3570697904, 'tag': 'IMPACT'}, {'confidence_score': 0.0590438917, 'tag': 'POLITICS'}]}","{'intent': {'news': 0.037, 'query': 0.427, 'spam': 0.241, 'marketing': 0.007, 'feedback': 0.288}}"
1710,hit:5257_conv:10514,2,I was too tired to mow the lawn and do garden work which me and my brother usually do together. As a result_comma_ he had to do it alone.,445,"I feel that way every day almost, Did you ever end up doing it?",69,3,2,1,0,...,0,0,0,0,0,2,"{'sentiment': {'negative': 0.358, 'neutral': 0.609, 'positive': 0.033}}","{'emotion': {'Excited': 0.0685982253, 'Fear': 0.2056618732, 'Angry': 0.0917739663, 'Happy': 0.2259420865, 'Sad': 0.338205889, 'Bored': 0.0698179597}}","{'taxonomy': [{'confidence_score': 0.517133534, 'tag': 'IMPACT'}, {'confidence_score': 0.3619345427, 'tag': 'ENTERTAINMENT'}, {'confidence_score': 0.0429505967, 'tag': 'ARTS & CULTURE'}]}","{'intent': {'news': 0.001, 'query': 0.584, 'spam': 0.186, 'marketing': 0.001, 'feedback': 0.228}}"
1711,hit:5257_conv:10514,3,I was too tired to mow the lawn and do garden work which me and my brother usually do together. As a result_comma_ he had to do it alone.,511,"No, my brother had to do it another even though we usually do it together.",80,3,1,1,0,...,0,0,0,0,0,2,"{'sentiment': {'negative': 0.807, 'neutral': 0.171, 'positive': 0.022}}","{'emotion': {'Angry': 0.4105899265, 'Sad': 0.2913022013, 'Excited': 0.069387258, 'Bored': 0.0713597947, 'Happy': 0.040714997, 'Fear': 0.1166458224}}","{'taxonomy': [{'confidence_score': 0.8585191965, 'tag': 'IMPACT'}, {'confidence_score': 0.047775194, 'tag': 'SPORTS'}, {'confidence_score': 0.044799041, 'tag': 'HEALTHY LIVING'}]}","{'intent': {'news': 0.007, 'query': 0.095, 'spam': 0.505, 'marketing': 0.004, 'feedback': 0.389}}"
1712,hit:5257_conv:10514,4,I was too tired to mow the lawn and do garden work which me and my brother usually do together. As a result_comma_ he had to do it alone.,445,What made you so tired??,24,3,2,1,0,...,0,0,0,0,0,2,"{'sentiment': {'negative': 0.6, 'neutral': 0.382, 'positive': 0.018}}","{'emotion': {'Angry': 0.0175678352, 'Excited': 0.012172804, 'Fear': 0.0535505307, 'Happy': 0.0098046176, 'Sad': 0.0561830539, 'Bored': 0.8507211585}}","{'taxonomy': [{'confidence_score': 0.5732952356, 'tag': 'ENTERTAINMENT'}, {'confidence_score': 0.0867252722, 'tag': 'TECH'}, {'confidence_score': 0.0825193003, 'tag': 'HEALTHY LIVING'}]}","{'intent': {'news': 0.002, 'query': 0.876, 'spam': 0.056, 'marketing': 0.001, 'feedback': 0.066}}"

In [9]:
emp_conv_df.groupby(['Empathy']).count()

,conv_id,utterance_idx,prompt,speaker_idx,utterance,ut_len,Talker,PL joy,PL trust,PL fear,PL surprise,PL sadness,PL disgust,PL anger,PL anticipation,PL intensity,Sentiment,Emotion,Taxonomy,Intent
Empathy,,,,,,,,,,,,,,,,,,,,
1,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
2,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144
3,533,533,533,533,533,533,533,533,533,533,533,533,533,533,533,533,533,533,533,533
4,835,835,835,835,835,835,835,835,835,835,835,835,835,835,835,835,835,835,835,835
5,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177

In [10]:
emp_conv_df['empathy'] = 0
emp_conv_df.loc[emp_conv_df['Empathy'] > 1, 'empathy'] = 1

In [11]:
emp_conv_df.groupby(['empathy']).count()

,conv_id,utterance_idx,prompt,speaker_idx,utterance,ut_len,Empathy,Talker,PL joy,PL trust,...,PL surprise,PL sadness,PL disgust,PL anger,PL anticipation,PL intensity,Sentiment,Emotion,Taxonomy,Intent
empathy,,,,,,,,,,,,,,,,,,,,,
0,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
1,1689,1689,1689,1689,1689,1689,1689,1689,1689,1689,...,1689,1689,1689,1689,1689,1689,1689,1689,1689,1689

##seeking-empathy or providing-emphaty dataset
0=> None 1=> seeking-empathy 2=> providing-empathy

In [15]:
df_seek_provid_train, df_seek_provid_test = train_test_split(iempathize_df, test_size=0.1, random_state=42)
df_seek_provid_train, df_seek_provid_val = train_test_split(df_seek_provid_train, test_size=0.1, random_state=42)

In [16]:
df = pd.DataFrame()
df['text'] = epitome_df['seeker_post']
df['label'] = 1

In [17]:
df_train, df_test = train_test_split(df, test_size=0.1, random_state=42)
df_train, df_val = train_test_split(df_train, test_size=0.1, random_state=42)

df_seek_provid_train = pd.concat([df_seek_provid_train, df_train], ignore_index=True)
df_seek_provid_test = pd.concat([df_seek_provid_test, df_test], ignore_index=True)
df_seek_provid_val = pd.concat([df_seek_provid_val, df_val], ignore_index=True)

In [18]:
df_seek_provid_train.groupby('label').count()

       text
label
0      2434
1      3846
2       761

In [19]:
df = pd.DataFrame()
df['text'] = epitome_df['response_post']
df['label'] = 0
df.loc[epitome_df['empathy'] == 1, 'label'] = 2

In [ ]:
df.groupby('label').count()

       text
label
0      1208
2      2479

In [20]:
df_train, df_test = train_test_split(df, test_size=0.1, random_state=42)
df_train, df_val = train_test_split(df_train, test_size=0.1, random_state=42)

df_seek_provid_train = pd.concat([df_seek_provid_train, df_train], ignore_index=True)
df_seek_provid_test = pd.concat([df_seek_provid_test, df_test], ignore_index=True)
df_seek_provid_val = pd.concat([df_seek_provid_val, df_val], ignore_index=True)

In [21]:
df_seek_provid_train.groupby('label').count()

       text
label
0      3413
1      3846
2      2768

In [22]:
news_df.head(2)

,message_id,response_id,article_id,empathy,distress,empathy_bin,distress_bin,essay
0,R_1hGrPtWM4SumG0U_1,R_1hGrPtWM4SumG0U,67,5.667,4.375,1,1,it is really diheartening to read about these immigrants from this article who drowned. it makes me feel anxious and upset how the whole ordeal happened. it is a terrible occurrence that this had to happen at the mediterranean sea. thankfully there were some survivors. the fact that babies were lost makes it that much more emotional to read all of this
1,R_1hGrPtWM4SumG0U_2,R_1hGrPtWM4SumG0U,86,4.833,4.875,1,1,the phone lines from the suicide prevention line surged after the election. it also climbed when robin williams committed suciide. thankfully there is this prevention line to help those in need who have sucidal thoughts but we need to condition people that committing sucide is a permanent solution to a temporary problem

In [23]:
df = pd.DataFrame()
df['text'] = news_df['essay']
df['label'] = 0
df.loc[news_df['empathy_bin'] == 1, 'label'] = 2

In [24]:
df.groupby('label').count()

       text
label
0       944
2       916

In [25]:
df_train, df_test = train_test_split(df, test_size=0.1, random_state=42)
df_train, df_val = train_test_split(df_train, test_size=0.1, random_state=42)

df_seek_provid_train = pd.concat([df_seek_provid_train, df_train], ignore_index=True)
df_seek_provid_test = pd.concat([df_seek_provid_test, df_test], ignore_index=True)
df_seek_provid_val = pd.concat([df_seek_provid_val, df_val], ignore_index=True)

In [26]:
df_seek_provid_train.groupby('label').count()

       text
label
0      4173
1      3846
2      3514

In [27]:
df = pd.DataFrame()
df['text'] = emp_conv_df[emp_conv_df['Talker']==1]['utterance']
df['label'] = 1

In [28]:
df_train, df_test = train_test_split(df, test_size=0.1, random_state=42)
df_train, df_val = train_test_split(df_train, test_size=0.1, random_state=42)

df_seek_provid_train = pd.concat([df_seek_provid_train, df_train], ignore_index=True)
df_seek_provid_test = pd.concat([df_seek_provid_test, df_test], ignore_index=True)
df_seek_provid_val = pd.concat([df_seek_provid_val, df_val], ignore_index=True)

In [29]:
df = pd.DataFrame()
df['text'] = emp_conv_df[emp_conv_df['Talker']==2]['utterance']
df['label'] = 0
df.loc[emp_conv_df['empathy'] == 1, 'label'] = 2

In [30]:
df_train, df_test = train_test_split(df, test_size=0.1, random_state=42)
df_train, df_val = train_test_split(df_train, test_size=0.1, random_state=42)

df_seek_provid_train = pd.concat([df_seek_provid_train, df_train], ignore_index=True)
df_seek_provid_test = pd.concat([df_seek_provid_test, df_test], ignore_index=True)
df_seek_provid_val = pd.concat([df_seek_provid_val, df_val], ignore_index=True)

In [31]:
df_seek_provid_train.groupby('label').count()

       text
label
0      4183
1      4560
2      4176

In [32]:
df_seek_provid_train.to_csv("train.csv")
df_seek_provid_test.to_csv("test.csv")
df_seek_provid_val.to_csv("val.csv")

##empathy detection in conversation

In [33]:
df = pd.DataFrame()
df['utterance'] = epitome_df['seeker_post']
df['utterance_idx'] = 1
df['empathy'] = epitome_df['empathy']
df['conv_id'] = epitome_df['Unnamed: 0']

In [34]:
df2 = pd.DataFrame()
df2['utterance'] = epitome_df['response_post']
df2['utterance_idx'] = 2
df2['empathy'] = epitome_df['empathy']
df2['conv_id'] = epitome_df['Unnamed: 0']

In [35]:
conv_df = pd.concat([df, df2], ignore_index=True)

In [36]:
conv_df = conv_df.sort_values(['conv_id']).reset_index()

In [37]:
conv_df

,index,utterance,utterance_idx,empathy,conv_id
0,0,Help. Help me. I dunno what I'm doing anymore,1,1,0
1,3687,"That's pretty vague, do you not know what you're doing in regards to a specific section of your life? Like school or work?",2,1,0
2,1,I'm done saying I love you to her because I don't want to hear a lie back to me. I feel so ugly and unwanted and unloved,1,0,1
3,3688,"idk what a Red pill means exactly but my advice to you is if she treating you right then fuck her there are billions of other girls out there, and if u feel like in love with her and just leave her then try to not care and you have to accept the fact that some girls(as well as some guys) will lie straight to your face for years without any remorse. my advice is stop caring before too late.",2,0,1
4,2,Always feel like I'm being criticized and mocked even when alone.... Does anyone else experience this?,1,1,2
...,...,...,...,...,...
7369,3684,"How do you handle people that pray on your depression/anxiety?. Sadly, I have friends that pray on my depression/anxiety. There's always something to disagree with or some snide comment to make. How do you guys cope with this? It makes me really anxious, which just leads to anger.",1,1,6042
7370,7372,"*hug* Whatever the situation is that's causing you to feel this way, please remember to exercise compassion towards yourself.",2,1,6044
7371,3685,I need a hug. I fucked up so bad. Thinking about ending it for once and for all. I could really use a hug right now,1,1,6044
7372,3686,"26 year old male, living at home, low income job, in school (parents paying for it), want to get married to girlfriend who graduates with nursing degree in 5 months. I feel like a deadbeat",1,0,6049
7373,7373,"I see what you mean, but imagine being 26, living at home with no job, absolutely no way to pay for school, and no girlfriend? I'm 26 with a decent job and live alone with no girlfriend. I tell myself that it's because I don't have a license due to a seizure disorder that I'm striking out with girls, which is probably true is some cases but I can't even see that girl being in one relationship for the rest of her life if she's picky like that.",2,0,6049

In [40]:
df_train, df_test = train_test_split(conv_df.conv_id.unique(), test_size=0.1, random_state=42)
df_train, df_val = train_test_split(df_train, test_size=0.1, random_state=42)

In [41]:
conv_df_train = conv_df[conv_df['conv_id'].isin(df_train)].copy()
conv_df_test = conv_df[conv_df['conv_id'].isin(df_test)].copy()
conv_df_val = conv_df[conv_df['conv_id'].isin(df_val)].copy()

In [42]:
df = pd.DataFrame()
df['utterance'] = emp_conv_df['utterance']
df['utterance_idx'] = emp_conv_df['utterance_idx']
df['empathy'] = emp_conv_df['empathy']
df['conv_id'] = emp_conv_df['conv_id']

In [45]:
_df_train, _df_test = train_test_split(df.conv_id.unique(), test_size=0.1, random_state=42)
_df_train, _df_val = train_test_split(_df_train, test_size=0.1, random_state=42)

In [47]:
df_train = df[df['conv_id'].isin(_df_train)].copy()
df_test = df[df['conv_id'].isin(_df_test)].copy()
df_val = df[df['conv_id'].isin(_df_val)].copy()

In [48]:
conv_df_train = pd.concat([conv_df_train, df_train], ignore_index=True)
conv_df_test = pd.concat([conv_df_test, df_test], ignore_index=True)
conv_df_val = pd.concat([conv_df_val, df_val], ignore_index=True)

In [49]:
conv_df_train.to_csv("train.csv")
conv_df_test.to_csv("test.csv")
conv_df_val.to_csv("val.csv")